Repository Go-Ride-Share/db-layer, pull requests merged in 2024-11, with the labels that each got.

#47 Added Continuous Deployment
  .github/workflows/docker-publish.yml
Labels: enhancement

#46 Improve validation and Code Cleanup
  DbAccessor/src/Account/VerifyLoginCredentials.cs
  DbAccessor/src/Messages/CreateConversation.cs
  DbAccessor/src/Messages/GetAllConversations.cs
  DbAccessor/src/Messages/PollConversation.cs
  DbAccessor/src/Messages/PostMessage.cs
  DbAccessor/src/Posts/CreatePost.cs
  DbAccessor/src/Posts/GetAllPosts.cs
  DbAccessor/src/Posts/GetPosts.cs
  DbAccessor/src/Posts/UpdatePost.cs
  DbAccessor/src/Shared/RequestObjects.cs
  DbAccessor/src/Shared/UserDB.cs
  DbAccessor/src/Shared/Utilities.cs
Labels: enhancement

#48 Release code for Sprint 2
  .github/workflows/docker-publish.yml
  DbAccessor/.dockerignore
  DbAccessor/DbAccessor.csproj
  DbAccessor/Dockerfile
  DbAccessor/Endpoints.yaml
  DbAccessor/RequestObjects.cs
  DbAccessor/sample.local.settings.json
  DbAccessor/src/Account/CreateAccount.cs
  DbAccessor/src/Account/VerifyLoginCredentials.cs
  DbAccessor/src/Messages/CreateConversation.cs
  DbAccessor/src/Messages/GetAllConversations.cs
  DbAccessor/src/Messages/PollConversation.cs
  DbAccessor/src/Messages/PostMessage.cs
  DbAccessor/src/Posts/CreatePost.cs
  DbAccessor/src/Posts/GetAllPosts.cs
  DbAccessor/src/Posts/GetPosts.cs
  DbAccessor/src/Posts/UpdatePost.cs
  DbAccessor/src/Shared/Program.cs
  DbAccessor/src/Shared/RequestObjects.cs
  DbAccessor/src/Shared/UserDB.cs
  DbAccessor/src/Shared/Utilities.cs
  DbAccessor/src/Users/EditUser.cs
  DbAccessor/src/Users/GetUser.cs
Labels: Feature 2

#49 WIP - Users Can Search For Posts
  DbAccessor/Endpoints.yaml
  DbAccessor/local.settings.json.example
  DbAccessor/src/Conversations/CreateConversation.cs
  DbAccessor/src/Conversations/GetConversations.cs
  DbAccessor/src/Conversations/GetMessages.cs
  DbAccessor/src/Conversations/PostMessages.cs
  DbAccessor/src/Conversations/RequestObjects.cs
  DbAccessor/src/Conversations/UserDB.cs
  DbAccessor/src/Posts/CreatePost.cs
  DbAccessor/src/Posts/FindPost.cs
  DbAccessor/src/Posts/GetAllPosts.cs
  DbAccessor/src/Posts/GetPost.cs
  DbAccessor/src/Posts/RequestObjects.cs
  DbAccessor/src/Posts/UpdatePost.cs
  DbAccessor/src/Shared/RequestObjects.cs
  DbAccessor/src/Shared/Utilities.cs
  DbAccessor/src/Users/CreateUser.cs
  DbAccessor/src/Users/EditUser.cs
  DbAccessor/src/Users/GetUser.cs
  DbAccessor/src/Users/LoginUser.cs
  DbAccessor/src/Users/RequestObjects.cs
Labels: enhancement

#51 Fix start a new conversation
  DbAccessor/src/Conversations/CreateConversation.cs
  DbAccessor/src/Conversations/RequestObjects.cs
  DbAccessor/src/Posts/FindPost.cs
  DbAccessor/src/Posts/GetPost.cs
  DbAccessor/src/Posts/GetPosts.cs
  DbAccessor/src/Posts/RequestObjects.cs
Labels: bug

#52 Add parameter to post search endpoint
  DbAccessor/Endpoints.yaml
  DbAccessor/src/Conversations/PostMessages.cs
  DbAccessor/src/Posts/FindPost.cs
  DbAccessor/src/Posts/RequestObjects.cs
Labels: enhancement

#54 Fix search endpoint
  DbAccessor/src/Posts/FindPost.cs
Labels: bug

#53 Combine get post endpoints
  DbAccessor/src/Posts/GetPost.cs
  DbAccessor/src/Posts/GetPosts.cs
  DbAccessor/src/Posts/UpdatePost.cs
Labels: enhancement

#56 Fixed Query for searching filter.
  DbAccessor/src/Posts/FindPost.cs
Labels: bug

#57 New Google Login
  DbAccessor/DbAccessor.csproj
  DbAccessor/Endpoints.yaml
  DbAccessor/src/Conversations/CreateConversation.cs
  DbAccessor/src/Conversations/GetConversations.cs
  DbAccessor/src/Conversations/GetMessages.cs
  DbAccessor/src/Conversations/PostMessages.cs
  DbAccessor/src/Conversations/RequestObjects.cs
  DbAccessor/src/Conversations/UserDB.cs
  DbAccessor/src/Posts/CreatePost.cs
  DbAccessor/src/Posts/FindPost.cs
  DbAccessor/src/Posts/GetPosts.cs
  DbAccessor/src/Posts/RequestObjects.cs
  DbAccessor/src/Posts/UpdatePost.cs
  DbAccessor/src/Shared/RequestObjects.cs
  DbAccessor/src/Shared/Utilities.cs
  DbAccessor/src/Users/CreateUser.cs
  DbAccessor/src/Users/EditUser.cs
  DbAccessor/src/Users/GetUser.cs
  DbAccessor/src/Users/GoogleLogin.cs
  DbAccessor/src/Users/PasswordLogin.cs
  DbAccessor/src/Users/RequestObjects.cs
  README.md
Labels: Feature
