Repository Go-Ride-Share/db-layer, pull requests merged in 2024-10, with the labels that each got.

#22 Fixed a bug, the create-post was not storing the name, departure date…
  DbAccessor/CreatePost.cs
Labels: bug

#24 Updated README with existing live endpoints
  README.md
Labels: documentation

#41 Create endpoint get all posts
  DbAccessor/GetAllPosts.cs
Labels: Feature

#45 Add docker files
  DbAccessor/.dockerignore
  DbAccessor/Dockerfile
Labels: Feature
